name: CI

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  build-examples-templates:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: 
          # For details, see: https://nodejs.dev/en/about/releases/
          # Maintance LTS. End Of Life: 2023-04-30
          - 14.x
          # Maintance LTS. End Of Life: 2023-09-11
          - 16.x
          # The following versions are not supported as 
          # they require react-script 5 which requires changes in 
          # streamlit-component-lib package.
          # For details, see: 
          # https://github.com/streamlit/streamlit/pull/6584
          # # Active LTS. End Of Life: 2025-04-30
          # - 18.x
          # # Current version
          # - 19.x

    name: Examples + Templates / node-version=${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check dependencies for examples
      run: ./dev.py examples-check-deps

    - name: Install node dependencies
      run: ./dev.py all-npm-install

    - name: Build frontend code
      run: ./dev.py all-npm-build

    - name: Build wheel packages
      run: |
        find examples -maxdepth 3 -name '__init__.py' |\
        xargs -n 1 sed -i 's/_RELEASE = False/_RELEASE = True/';
        ./dev.py examples-python-build-package
    
    - name: Upload wheel packages
      uses: actions/upload-artifact@v3
      with:
        name: all-wheel
        path: dist/*.whl
        if-no-files-found: error
