name: CI

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: 
          # For details, see: https://nodejs.dev/en/about/releases/
          # Maintance LTS. End Of Life: 2023-04-30
          - 14.x
          # Maintance LTS. End Of Life: 2023-09-11
          - 16.x
          # The following versions are not supported as 
          # they require react-script 5 which requires changes in 
          # streamlit-component-lib package.
          # For details, see: 
          # https://github.com/streamlit/streamlit/pull/6584
          # # Active LTS. End Of Life: 2025-04-30
          # - 18.x
          # # Current version
          # - 19.x
        cwd:
          - ./template
          - ./template-reactless

    name:  Build / node-version=${{ matrix.node-version }} / cwd=${{ matrix.cwd }}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      working-directory: ${{ matrix.cwd }}/my_component/frontend
      run: npm install

    - name: Build frontend code
      working-directory: ${{ matrix.cwd }}//my_component/frontend
      run: npm run build
